server:
  port: 8080

spring:
  application:
     name:  home-controller
  freemarker:
    suffix: .ftl

feign:
  client:
     config:
       default:
        loggerLevel: basic
        connectTimeout: 8000
        readTimeout: 1000
        logger-level: FULL 
  ratelimiter:
    instances:
      basic:
        limitForPeriod: 1000s
        limitRefreshPeriod: 1
        timeoutDuration: 5s
#feign.compression.request.enabled: true
#feign.compression.response.enabled: true
logging.level.frontend.service.ApiGatewayRequestUri: DEBUG

